### ISSUE TITLE
Shadow Flicker Module 

### ISSUE THREAD

**Issue by alopez04** [NREL/reVX#149]
**Bug Description**
The output shadow flier raster is 9-meter, but the data is aggregated to big blocks instead of showing the detailed flicker from turbines. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/9019826/172441110-3737f13d-d1ef-42ad-a530-01c3020e880e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/9019826/172441299-443cf35b-65f3-42dd-ab38-2f314e845a33.png)

**System (please complete the following information):**
- Eagle 

**Additional context**
![image](https://user-images.githubusercontent.com/9019826/172441376-334c6357-d1aa-4e57-8bf5-1eba7126cbb7.png)

**Charge code**
WEPG.10348.08.01.06

**Comment by grantbuster** [comment]
@alopez04, cannot reproduce, test rasters look fine, running with your requested config with the big turbine (160m hh) yields [this error message](https://github.com/NREL/reVX/blob/f6f8d7eba65c2eff17fe3041201cb4dd922c9ae9/reVX/turbine_flicker/turbine_flicker.py#L186), but upping the `FLICKER_ARRAY_LEN` works fine (now pushed to main). 

Here's the config i used:
```
{
    "execution_control": {
        "allocation": "rev",
        "option": "eagle",
        "walltime": 4,
        "feature": "--qos=high",
        "max_workers": null
    },
    "name": "flicker_160m_30hr_yr_640",
    "excl_fpath": "./conus_buildings.h5",
    "res_fpath": "/datasets/WIND/conus/v1.0.0/wtk_conus_2012.h5",
    "building_layer": "conus_bld_perc",
    "hub_height": 160,
    "out_layer": "flicker_inclusions",
    "tm_dset": "techmap_wind",
    "building_threshold": 0,
    "flicker_threshold": 30,
    "resolution": 640,
    "log_level": "INFO"
}
```

Where `./conus_buildings.h5` is a copy of `/shared-projects/rev/exclusions/conus_buildings.h5`. The code ended up remaking the techmap because i copied the dataset name over wrong, but i checked against the old techmap and that shouldnt make a difference. 

My debug dir: `/scratch/gbuster/rev/test_flicker/`

Sample outputs:
![image](https://user-images.githubusercontent.com/12700356/173480684-cb0cfe51-31c5-413e-a0df-ed75911f73ed.png)
![image](https://user-images.githubusercontent.com/12700356/173481007-a4d5e65c-95b3-4552-9242-437b4f3dee4d.png)

**Comment by alopez04** [comment]
Thanks, Grant! I'll have Travis give this a go and let you know if we run into other issues given our large turbine set.
